language: node_js
node_js:
  - 12.3.1
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install: echo "install happens as part of setup"
script: yarn setup
after_script: npx codecov@3
branches:
  only: master
